// Package plan implements the diff engine: it compares the live Kong state with
// the desired state coming from the canvas and produces an ordered list of
// Admin API operations, in the spirit of `terraform plan`.
package plan

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/gefferson/kong-flow/backend/internal/kong"
)

type OpType string

const (
	OpCreate OpType = "create"
	OpUpdate OpType = "update"
	OpDelete OpType = "delete"
)

// DraftPrefix marks ids generated by the canvas for entities that do not exist
// in Kong yet.
const DraftPrefix = "draft:"

func IsDraftID(id string) bool { return id == "" || strings.HasPrefix(id, DraftPrefix) }

type FieldChange struct {
	Field string `json:"field"`
	From  any    `json:"from"`
	To    any    `json:"to"`
}

type Op struct {
	Type     OpType        `json:"type"`
	Kind     string        `json:"kind"`
	EntityID string        `json:"entity_id"` // kong id, or draft id for creates
	Label    string        `json:"label"`
	Before   kong.Entity   `json:"before,omitempty"`
	After    kong.Entity   `json:"after,omitempty"`
	Payload  kong.Entity   `json:"payload,omitempty"` // what is actually sent to Kong
	Changes  []FieldChange `json:"changes,omitempty"`
}

type Summary struct {
	Create int `json:"create"`
	Update int `json:"update"`
	Delete int `json:"delete"`
}

type Plan struct {
	Ops     []Op    `json:"ops"`
	Summary Summary `json:"summary"`
	// Conflicts are entities another editor changed in Kong after this canvas
	// read them. Applying anyway would silently undo that other work.
	Conflicts []Conflict `json:"conflicts,omitempty"`
	// Ignored are entities that exist in Kong but that this canvas never saw,
	// so they are left strictly alone instead of being deleted.
	Ignored []Ignored `json:"ignored,omitempty"`
}

func (p Plan) IsEmpty() bool { return len(p.Ops) == 0 }

// HasConflicts reports whether applying would overwrite somebody else's work.
func (p Plan) HasConflicts() bool { return len(p.Conflicts) > 0 }

// Options tunes how a plan is built.
type Options struct {
	// Baseline is the live state the canvas was loaded from — what the user
	// actually saw. With it set, a plan can tell "the user removed this" apart
	// from "somebody else added this while the canvas was open", and can spot
	// entities that drifted underneath the canvas. A nil Baseline means the
	// canvas is assumed to have seen everything that is live now, which is the
	// single-editor behaviour.
	Baseline kong.State
}

// Conflict reports an entity that changed in Kong after this canvas read it,
// on which the plan nevertheless wants to act.
type Conflict struct {
	Kind     string `json:"kind"`
	EntityID string `json:"entity_id"`
	Label    string `json:"label"`
	Op       OpType `json:"op"`     // what this plan wanted to do with it
	Reason   string `json:"reason"` // changed | deleted
	// Changes is what the other editor did: baseline → live.
	Changes []FieldChange `json:"changes,omitempty"`
}

// Ignored is an entity present in Kong that this canvas never loaded — created
// by somebody else after the canvas opened. It is never deleted, only reported.
type Ignored struct {
	Kind     string `json:"kind"`
	EntityID string `json:"entity_id"`
	Label    string `json:"label"`
}

const (
	ReasonChanged = "changed"
	ReasonDeleted = "deleted"
)

// readOnly fields are server-managed and never sent or diffed.
var readOnly = map[string]bool{
	"created_at": true, "updated_at": true, "id": true, "ws_id": true,
}

// Build diffs current (live) against desired (canvas). Kinds missing from
// desired are left untouched, so a partial canvas never deletes what it does
// not know about.
func Build(current, desired kong.State) Plan {
	return BuildWith(current, desired, Options{})
}

// BuildWith is Build with the canvas's baseline taken into account, which is
// what makes two people editing the same Kong safe: anything that appeared in
// Kong after this canvas loaded is left alone rather than deleted, and anything
// that changed underneath it is reported as a conflict rather than reverted.
func BuildWith(current, desired kong.State, opt Options) Plan {
	p := Plan{Ops: []Op{}}
	scoped := opt.Baseline != nil
	for _, kind := range kong.Kinds {
		want, present := desired[kind]
		if !present {
			continue
		}
		have := current[kind]
		haveByID := map[string]kong.Entity{}
		for _, e := range have {
			haveByID[e.ID()] = e
		}
		baseByID := map[string]kong.Entity{}
		if scoped {
			for _, e := range opt.Baseline[kind] {
				baseByID[e.ID()] = e
			}
		}
		// drift reports what another editor did to an entity since the canvas
		// read it, or nil when it is untouched.
		drift := func(id string, live kong.Entity) []FieldChange {
			base, known := baseByID[id]
			if !scoped || !known {
				return nil
			}
			return diffFields(base, live)
		}
		seen := map[string]bool{}

		for _, d := range want {
			id := d.ID()
			if IsDraftID(id) {
				p.Ops = append(p.Ops, Op{
					Type: OpCreate, Kind: kind, EntityID: id,
					Label: label(kind, d), After: d, Payload: sanitize(d),
				})
				continue
			}
			cur, ok := haveByID[id]
			if !ok {
				// The canvas thinks it exists but Kong does not — recreate it.
				// When the canvas did see it, its disappearance is somebody
				// else's delete, not a drift the user asked to undo.
				if _, known := baseByID[id]; scoped && known {
					p.Conflicts = append(p.Conflicts, Conflict{
						Kind: kind, EntityID: id, Label: label(kind, d),
						Op: OpCreate, Reason: ReasonDeleted,
					})
				}
				p.Ops = append(p.Ops, Op{
					Type: OpCreate, Kind: kind, EntityID: id,
					Label: label(kind, d), After: d, Payload: sanitize(d),
				})
				continue
			}
			seen[id] = true
			changes := diffFields(cur, d)
			if len(changes) == 0 {
				continue
			}
			if moved := drift(id, cur); len(moved) > 0 {
				p.Conflicts = append(p.Conflicts, Conflict{
					Kind: kind, EntityID: id, Label: label(kind, cur),
					Op: OpUpdate, Reason: ReasonChanged, Changes: moved,
				})
			}
			// PATCH is partial, so only changed fields are sent. Targets are
			// immutable in Kong and get replaced, so they need the whole entity.
			payload := kong.Entity{}
			if kind == "targets" {
				payload = sanitize(d)
			} else {
				for _, ch := range changes {
					payload[ch.Field] = ch.To
				}
			}
			p.Ops = append(p.Ops, Op{
				Type: OpUpdate, Kind: kind, EntityID: id, Label: label(kind, cur),
				Before: cur, After: d, Payload: payload, Changes: changes,
			})
		}

		for _, cur := range have {
			id := cur.ID()
			if seen[id] {
				continue
			}
			if scoped {
				if _, known := baseByID[id]; !known {
					// Never in this canvas, so its absence is not a removal —
					// somebody created it while the canvas was open.
					p.Ignored = append(p.Ignored, Ignored{Kind: kind, EntityID: id, Label: label(kind, cur)})
					continue
				}
				if moved := drift(id, cur); len(moved) > 0 {
					p.Conflicts = append(p.Conflicts, Conflict{
						Kind: kind, EntityID: id, Label: label(kind, cur),
						Op: OpDelete, Reason: ReasonChanged, Changes: moved,
					})
				}
			}
			p.Ops = append(p.Ops, Op{
				Type: OpDelete, Kind: kind, EntityID: id,
				Label: label(kind, cur), Before: cur, Payload: cur,
			})
		}
	}
	sortOps(p.Ops)
	for _, op := range p.Ops {
		switch op.Type {
		case OpCreate:
			p.Summary.Create++
		case OpUpdate:
			p.Summary.Update++
		case OpDelete:
			p.Summary.Delete++
		}
	}
	return p
}

// sortOps orders creates/updates by dependency (services before routes before
// plugins) and deletes in the reverse order, so referenced entities outlive
// their referrers.
func sortOps(ops []Op) {
	rank := map[string]int{}
	for i, k := range kong.Kinds {
		rank[k] = i
	}
	phase := func(o Op) int {
		if o.Type == OpDelete {
			return 1
		}
		return 0
	}
	sort.SliceStable(ops, func(i, j int) bool {
		pi, pj := phase(ops[i]), phase(ops[j])
		if pi != pj {
			return pi < pj
		}
		ri, rj := rank[ops[i].Kind], rank[ops[j].Kind]
		if ri != rj {
			if pi == 1 {
				return ri > rj
			}
			return ri < rj
		}
		return false
	})
}

// diffFields compares only the fields the canvas actually sent, so unknown or
// version-specific Kong fields are never clobbered.
func diffFields(cur, want kong.Entity) []FieldChange {
	var out []FieldChange
	keys := make([]string, 0, len(want))
	for k := range want {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if readOnly[k] {
			continue
		}
		to := want[k]
		from := cur[k]
		if equivalent(from, to) {
			continue
		}
		out = append(out, FieldChange{Field: k, From: from, To: to})
	}
	return out
}

// equivalent treats nil / absent / empty collections as the same value, which
// is how Kong reports unset optional fields.
func equivalent(a, b any) bool {
	if isEmpty(a) && isEmpty(b) {
		return true
	}
	an, aok := toFloat(a)
	bn, bok := toFloat(b)
	if aok && bok {
		return an == bn
	}
	return reflect.DeepEqual(normalize(a), normalize(b))
}

func toFloat(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case float32:
		return float64(n), true
	case int:
		return float64(n), true
	case int64:
		return float64(n), true
	}
	return 0, false
}

func isEmpty(v any) bool {
	switch t := v.(type) {
	case nil:
		return true
	case []any:
		return len(t) == 0
	case map[string]any:
		return len(t) == 0
	case string:
		return t == ""
	}
	return false
}

// normalize collapses foreign-key objects to their id so `{"id":"x"}` and
// `"x"` compare equal, and drops read-only keys from nested maps.
func normalize(v any) any {
	switch t := v.(type) {
	case map[string]any:
		if id, ok := t["id"].(string); ok && len(t) <= 2 {
			return id
		}
		out := map[string]any{}
		for k, val := range t {
			if readOnly[k] {
				continue
			}
			if isEmpty(val) {
				continue
			}
			out[k] = normalize(val)
		}
		return out
	case []any:
		out := make([]any, 0, len(t))
		for _, val := range t {
			out = append(out, normalize(val))
		}
		return out
	}
	return v
}

// sanitize strips server-managed fields from a create payload but keeps a
// caller-provided real id (useful when re-creating something deleted outside).
func sanitize(e kong.Entity) kong.Entity {
	out := kong.Entity{}
	for k, v := range e {
		if readOnly[k] {
			continue
		}
		if isEmpty(v) {
			continue
		}
		out[k] = v
	}
	if id := e.ID(); id != "" && !IsDraftID(id) {
		out["id"] = id
	}
	return out
}

func label(kind string, e kong.Entity) string {
	singular := strings.TrimSuffix(kind, "s")
	if n := e.Name(); n != "" {
		return fmt.Sprintf("%s %s", singular, n)
	}
	for _, k := range []string{"username", "target", "id"} {
		if v := e.Str(k); v != "" {
			return fmt.Sprintf("%s %s", singular, v)
		}
	}
	return singular
}
